import { fetchJolpica } from './jolpicaClient'
import { supabase } from './supabaseClient'

type Entity = 'seasons' | 'circuits' | 'teams' | 'drivers' | 'races' | 'results' | 'qualifying_results' | 'sprint_results' | 'pitstops' | 'laps' | 'driver_standings' | 'constructor_standings' | 'status'
type Row = Record<string, unknown>
export type ImportResult = { processed: number; created: number; updated: number; errors: string[] }

const asRows = (value: unknown): Row[] => Array.isArray(value) ? value as Row[] : []
const field = (row: Row, key: string): unknown => row[key]
const objectField = (row: Row, key: string): Row => { const value = field(row, key); return value && typeof value === 'object' ? value as Row : {} }
const nested = (row: Row, parent: string, key: string): unknown => field(objectField(row, parent), key)
const refRow = (externalRef: string, values: Row): Row => ({ ...values, external_ref: externalRef, source: 'jolpica', is_overridden: false })
const empty = (): ImportResult => ({ processed: 0, created: 0, updated: 0, errors: [] })

function list(response: Row, table: string, key: string): Row[] { return asRows(nested(response, 'MRData', table) instanceof Object ? objectField(objectField(response, 'MRData'), table)[key] : undefined) }
async function ids(table: string, refs: string[]) { const unique = [...new Set(refs)]; if (!unique.length) return new Map<string, string>(); const { data, error } = await supabase!.from(table).select('id, external_ref').in('external_ref', unique); if (error) throw new Error(`${table}: ${error.message}`); return new Map((data ?? []).map((row) => [row.external_ref as string, row.id as string])) }
async function upsert(table: string, rows: Row[]): Promise<ImportResult> { if (!supabase) throw new Error('Supabase is disabled. Set VITE_USE_SUPABASE=true.'); if (!rows.length) return empty(); const refs = rows.map((row) => row.external_ref as string); const { data: existing, error: lookupError } = await supabase.from(table).select('external_ref').in('external_ref', refs); if (lookupError) throw new Error(`${table}: ${lookupError.message}`); const old = new Set((existing ?? []).map((row) => row.external_ref)); const { error } = await supabase.from(table).upsert(rows, { onConflict: 'external_ref' }); if (error) throw new Error(`${table}: ${error.message}`); return { processed: rows.length, created: rows.filter((row) => !old.has(row.external_ref)).length, updated: rows.filter((row) => old.has(row.external_ref)).length, errors: [] } }
async function seasonId(year: string) { const { data } = await supabase!.from('seasons').select('id').eq('year', Number(year)).single(); if (!data) throw new Error(`Season ${year} could not be resolved.`); return data.id as string }

export async function importEntity(entity: Entity, season: string, round = ''): Promise<ImportResult> {
  if (!supabase) throw new Error('Supabase is disabled. Set VITE_USE_SUPABASE=true.')
  const path = entity === 'seasons' ? 'seasons' : entity === 'circuits' ? 'circuits' : entity === 'teams' ? 'constructors' : entity === 'drivers' ? 'drivers' : entity === 'races' ? `${season}/races` : entity === 'status' ? 'status' : `${season}/${round ? `${round}/` : ''}${entity === 'results' ? 'results' : entity === 'qualifying_results' ? 'qualifying' : entity === 'sprint_results' ? 'sprint' : entity === 'pitstops' ? 'pitstops' : entity === 'laps' ? 'laps' : entity === 'driver_standings' ? 'driverstandings' : 'constructorstandings'}`
  const response = await fetchJolpica<Row>(`${path}?limit=1000`)
  if (entity === 'seasons') return upsert('seasons', list(response, 'SeasonTable', 'Seasons').map((row) => refRow(String(field(row, 'season')), { year: Number(field(row, 'season')), url: field(row, 'url') })))
  if (entity === 'circuits') return upsert('circuits', list(response, 'CircuitTable', 'Circuits').map((row) => { const location = objectField(row, 'Location'); return refRow(String(field(row, 'circuitId')), { name: field(row, 'circuitName'), location: field(location, 'locality'), country: field(location, 'country'), lat: Number(field(location, 'lat')) || null, lng: Number(field(location, 'long')) || null, url: field(row, 'url') }) }))
  if (entity === 'teams') return upsert('teams', list(response, 'ConstructorTable', 'Constructors').map((row) => refRow(String(field(row, 'constructorId')), { name: field(row, 'name'), nationality: field(row, 'nationality'), url: field(row, 'url') })))
  if (entity === 'drivers') return upsert('drivers', list(response, 'DriverTable', 'Drivers').map((row) => refRow(String(field(row, 'driverId')), { driver_ref: field(row, 'driverId'), code: field(row, 'code'), permanent_number: field(row, 'permanentNumber'), given_name: field(row, 'givenName'), family_name: field(row, 'familyName'), dob: field(row, 'dateOfBirth') || null, nationality: field(row, 'nationality'), url: field(row, 'url') })))
  if (entity === 'status') return upsert('status', list(response, 'StatusTable', 'Status').map((row) => refRow(String(field(row, 'statusId')), { status_text: field(row, 'status') })))
  await importEntity('seasons', season)
  if (entity === 'races') { const races = list(response, 'RaceTable', 'Races'); const circuitRows = races.map((race) => { const circuit = objectField(race, 'Circuit'); const location = objectField(circuit, 'Location'); return refRow(String(field(circuit, 'circuitId')), { name: field(circuit, 'circuitName'), location: field(location, 'locality'), country: field(location, 'country'), url: field(circuit, 'url') }) }); await upsert('circuits', circuitRows); const sid = await seasonId(season); const circuitIds = await ids('circuits', circuitRows.map((row) => String(row.external_ref))); return upsert('races', races.map((race) => { const circuit = objectField(race, 'Circuit'); return refRow(`${season}-${field(race, 'round')}`, { season_id: sid, round: Number(field(race, 'round')), circuit_id: circuitIds.get(String(field(circuit, 'circuitId'))) ?? null, name: field(race, 'raceName'), date: field(race, 'date'), time: field(race, 'time') || null, url: field(race, 'url') }) })) }
  await importEntity('races', season); await importEntity('drivers', season); await importEntity('teams', season); await importEntity('status', season); const sid = await seasonId(season); const raceData = (await supabase.from('races').select('id, external_ref').eq('season_id', sid)).data ?? []; const raceIds = new Map(raceData.map((row) => [row.external_ref as string, row.id as string])); const rawRaces = list(response, 'RaceTable', 'Races'); const key = entity === 'results' ? 'Results' : entity === 'qualifying_results' ? 'QualifyingResults' : entity === 'sprint_results' ? 'SprintResults' : entity === 'pitstops' ? 'PitStops' : 'Laps'; const items = rawRaces.flatMap((race) => asRows(field(race, key)).map((item) => ({ item, race }))); const driverIds = await ids('drivers', items.map(({ item }) => String(nested(item, 'Driver', 'driverId')))); const teamIds = await ids('teams', items.map(({ item }) => String(nested(item, 'Constructor', 'constructorId')))); const rows = items.map(({ item, race }) => { const raceRef = `${season}-${field(race, 'round')}`; const driverRef = String(nested(item, 'Driver', 'driverId')); const teamRef = String(nested(item, 'Constructor', 'constructorId')); const common = { race_id: raceIds.get(raceRef), driver_id: driverIds.get(driverRef), team_id: teamIds.get(teamRef) }; if (entity === 'results') return refRow(`${raceRef}-${driverRef}`, { ...common, grid: Number(field(item, 'grid')), position: Number(field(item, 'position')), position_text: field(item, 'positionText'), points: Number(field(item, 'points')), laps: Number(field(item, 'laps')) }); if (entity === 'qualifying_results') return refRow(`${raceRef}-${driverRef}`, { ...common, position: Number(field(item, 'position')), q1: field(item, 'Q1') || null, q2: field(item, 'Q2') || null, q3: field(item, 'Q3') || null }); if (entity === 'sprint_results') return refRow(`${raceRef}-${driverRef}`, { ...common, grid: Number(field(item, 'grid')), position: Number(field(item, 'position')), points: Number(field(item, 'points')), laps: Number(field(item, 'laps')) }); if (entity === 'pitstops') return refRow(`${raceRef}-${driverRef}-${field(item, 'stop')}`, { ...common, stop_number: Number(field(item, 'stop')), lap: Number(field(item, 'lap')), time: field(item, 'time'), duration_ms: Math.round(Number(field(item, 'duration')) * 1000) }); return refRow(`${raceRef}-${driverRef}-${field(item, 'number')}`, { ...common, lap_number: Number(field(item, 'number')), position: Number(field(item, 'position')), time_ms: Number(nested(item, 'Time', 'millis')) || null }) }); return upsert(entity, rows.filter((row) => row.race_id && row.driver_id))
}
export async function writeImportLog(entity: Entity, season: string, result: ImportResult, error?: string) { if (!supabase) return; const { data } = await supabase.auth.getSession(); await supabase.from('import_logs').insert({ endpoint: `${season}/${entity}`, mode: 'single', entity_type: entity, records_processed: result.processed, records_created: result.created, records_updated: result.updated, errors: error ? [error] : result.errors, triggered_by: data.session?.user.id ?? null }) }
